# Generated by Django 5.2.11 on 2026-03-06 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_booking_status_alter_booking_seat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='theater',
            name='rows',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='theater',
            name='seats_per_row',
            field=models.IntegerField(default=12),
        ),
    ]
