# Generated by Django 5.2.11 on 2026-03-24 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_seat_locked_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='booking',
        ),
        migrations.AddField(
            model_name='payment',
            name='booking',
            field=models.ManyToManyField(related_name='payments', to='movies.booking'),
        ),
    ]
