# Generated by Django 5.2.11 on 2026-03-24 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0011_remove_payment_booking_payment_booking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='booking',
            new_name='bookings',
        ),
    ]
