# Generated by Django 5.2.11 on 2026-03-28 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0012_rename_booking_payment_bookings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='bookings',
        ),
        migrations.AddField(
            model_name='booking',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='movies.payment'),
        ),
    ]
