# Generated by Django 5.2.11 on 2026-03-30 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0013_remove_payment_bookings_booking_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('otp', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
